### ISSUE TITLE
TypeError: $ is not a function

### ISSUE THREAD

**Issue by dioptryk** [kwarchalowski/tvpVODdownloader#1]
When running on Ubuntu 18, I immediately get the following:
`
TypeError: $ is not a function
in allVidsIdScraper.js:25:17
`
Does it require some specific version of whole node/npm environment? I got node 14.20.1 and npm 6.14.17. During installation npm said that Puppeteer and Request are deprecated.

**Comment by kwarchalowski** [comment]
Hey there :)

> Does it require some specific version of whole node/npm environment? 

I don't think so, I've already started looking into that issue and found out there's a problem with different module. [Cheerio](https://cheerio.js.org/) trying to access HTML elements that are not loaded yet.

I've started working on a fix. Found more issues of course. I will update some dependencies as well.

To be honest with you - this code is garbage. But yea, it **should** work when I fix it. Somehow. ^_^

**Comment by liamdj23** [comment]
Any updates?

**Comment by kylevessPL** [comment]
Seems like he fixed it but did not publish the updated version on npmjs.
Install from GitHub directly using:
`npm install https://github.com/kwarchalowski/tvpVODdownloader.git`

Meanwhile, I suggest switching to [ytdl](https://github.com/ytdl-patched/ytdl-patched).

**Comment by kwarchalowski** [comment]
Indeed, it's pretty much an obsolete package. I have no intentions to fix it as the VOD platform is constantly changing.
Other than that, this package wasn't very flexible from the beginning.

I have marked it as DEPRECATED so it won't confuse anyone anymore.

As @kylevessPL said - I suggest switching to solution that is actually working and being maintained :)

Thank you, cheers
